import type { Metadata } from 'next';
import { Providers } from '@/app/providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html prefix="og: http://ogp.me/ns#" lang="ja">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
